#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 22 10:54:25 2015
@author: bwb0de

Converte arquivos MP3, MP4 e OGV em OGG... E copia os arquivos convertidos para o Desktop.

"""

from subprocess import Popen
from sys import argv, exit
from os import walk, path, remove

MAX_INSTANCES=50
PATH = argv[1]
PATH2COUTER = '/home/bwb0de/.scrips/mp3TOogg.counter'
PATH2COUTER = '/home/bwb0de/.scrips/mp4TOmkv.counter'
PATH2COUTER = '/home/bwb0de/.scrips/mp3TOogg.counter'
INSTANCES = []
FILELIST=[]
FILELIST2RM=[]

#ffmpeg -i "${FILE}"  "${FILE%.mp4}.ogg"
#ffmpeg -i LostInTranslation.mkv -vcodec copy -acodec copy LostInTranslation.mp4
#ffmpeg -i «video» -acodec libmp3lame -ab 128 «saída».mp3

def convertMp3ToOgg(FN):
	cmd = ['ffmpeg', '-i', FN, FN.replace(".mp3", ".ogg"), "-n", "-loglevel", "quiet"]
	cmd = ['ffmpeg', '-i', FN, '-vn', '-acodec', 'libvorbis', FN.replace(".mp4", ".ogg"), "-n", "-loglevel", "quiet"]	
	cmd = ['ffmpeg', '-i', FN, '-acodec', 'copy', '-vn', FN.replace(".ogg", ".ogg.ogg"), "-n", "-loglevel", "quiet"]
	sp = Popen(cmd)
	return sp


for root, dirs, files in walk(PATH):
	for f in files:
		if f.find(".mp3") != -1:
			FILELIST.append(path.join(root, f))

for root, dirs, files in walk(PATH):
	for f in files:
		if f.find(".mp4") != -1:
			FILELIST.append(path.join(root, f))

#for root, dirs, files in walk(PATH):
#	for f in files:
#		if f.find(".ogg") != -1:
#			FILELIST2RM.append(path.join(root, f))

print "%s arquivos MP3 encontrados." % len(FILELIST)
#print "Destes, %s, já convertidos." % len(FILELIST2RM)

for FDONE in FILELIST2RM:
	FILELIST2RM.remove(FDONE)
	try:
		FILELIST.remove(FDONE.replace(".ogg", ".mp3"))
	except: pass

#print "%s arquivos para converter..." % len(FILELIST)
#print "%s arquivos OGV encontrados." % len(FILELIST)
#print "%s arquivos MP4 encontrados." % len(FILELIST)

FILELIST.sort()
FILELIST.reverse()

while True:
	if len(FILELIST) == 0:
		break
	else:
		if len(INSTANCES) < MAX_INSTANCES:
			FN = FILELIST.pop()
			#FILELIST2RM.append(FN)
			print u"Convertendo: %s" % FN.decode("utf8")
			INSTANCES.append(convertMp3ToOgg(FN))
		else:
			for sp in INSTANCES:
				if sp.poll() != None:
					INSTANCES.remove(sp)
