#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

import argparse
from os import system as sh
from os import linesep as nl
from os import listdir as ls
from subprocess import check_output as sh2

script_nfo="""
Script de clonagem de diretórios e arquivos...
"""

parser = argparse.ArgumentParser(description=script_nfo)
parser.add_argument("fonte", help="defina o diretório a ser clonado...")
parser.add_argument("destino", help="e o local para onde deverá ser clonado...")
args = parser.parse_args()


def check_item_list(item, lista):
	try:
		lista.index(item)
		return True
	except:
		return False

def main():
	sh('find "{}" -type d > /tmp/clone_script_dir'.format(args.fonte))
	estrutura_de_diretorios = sh2('cat < /tmp/clone_script_dir', shell=True)
	estrutura_de_diretorios = estrutura_de_diretorios.decode("utf-8").split(nl)[:-1]
	for line in estrutura_de_diretorios:
		sh('mkdir -p "{}"'.format(args.destino+'/'+line))
	sh('find "{}" -type f > /tmp/clone_script_files'.format(args.fonte))
	arquivos = sh2('cat < /tmp/clone_script_files', shell=True)
	arquivos = arquivos.decode("utf-8").split(nl)[:-1]
	for line in arquivos:
		sh('ln "{}" "{}"'.format(line, args.destino+'/'+line))
	return 0

if __name__ == '__main__':
	main()
