#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 22 10:54:25 2015
@author: bwb0de

Converte arquivos MP3 em OGG e apaga os arquivos MP3 ao final do processo...

"""

from subprocess import Popen
from sys import argv, exit
from os import walk, path, remove

MAX_INSTANCES=50
PATH = argv[1]
INSTANCES = []
FILELIST=[]
FILELIST2RM=[]

def convertMp3ToOgg(FN):
	
	sp = Popen(cmd)
	return sp


#ffmpeg -i [video] -acodec libvorbis [saida.ogg]



FILELIST.sort()
FILELIST.reverse()

while True:
	if len(FILELIST) == 0:
		break
	else:
		if len(INSTANCES) < MAX_INSTANCES:
			FN = FILELIST.pop()
			#FILELIST2RM.append(FN)
			print u"Convertendo: %s" % FN.decode("utf8")
			INSTANCES.append(convertMp3ToOgg(FN))
		else:
			for sp in INSTANCES:
				if sp.poll() != None:
					INSTANCES.remove(sp)
