#!/bin/bash
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

if test $# -lt 1;
	then
	echo "É necessário fornecer um diretório alvo para efetuar a limpeza..."
	exit 1
fi

if test -d "$1";
	then
	echo "Procurando por arquivos 'desktop.ini'..."
	find "$1" -type f -iname "desktop.ini" -exec rm {} \;
	echo "Procurando por arquivos 'thumbs.db'..."
	find "$1" -type f -iname "thumbs.db" -exec rm {} \;
else
	echo "O alvo deve ser um diretório..."
	exit 1
fi





